INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "enthent_l1" , "EnthEnt" , "L1" , 275 , "east" , "true" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l1_l2" , "l1" , "l2" , 381 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "justent_l3" , "JustEnt" , "L3" , 156 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l2_l3" , "L2" , "L3" , 464 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l3_l4" , "L3" , "L4" , 462 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "learent_l4" , "LearEnt" , "L4" , 175 , "east" , "true" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l4_l5" , "L4" , "L5" , 601 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l5_l6" , "L5" , "L6" , 1001 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l6_l7" , "L6" , "L7" , 1057 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "certent_l7" , "CertEnt" , "L7" , 759 , "east" , "true" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l7_l8" , "L7" , "L8" , 1030 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l8_l9" , "L8" , "L9" , 99999 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l9_l10" , "L9" , "L10" , 99999 , "west" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l10_l11" , "L10" , "L11" , 99999 , "west" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l8_l11" , "L8" , "L11" , 935 , "west" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "inteent_l11" , "InteEnt" , "L11" , 742 , "west" , "true" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l11_l12" , "L11" , "L12" , 943 , "west" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "initent_l12" , "InitEnt" , "L12" , 262 , "west" , "true" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "leadent_l13" , "LeadEnt" , "L13" , 82 , "east" , "true" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l13_l14" , "L13" , "L14" , 454 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "judgent_l14" , "JudgEnt" , "L14" , 438 , "east" , "true" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l14_l15" , "L14" , "L15" , 321 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "respent_l15" , "RespEnt" , "L15" , 854 , "east" , "true" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l15_l16" , "L15" , "L16" , 662 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l16_l17" , "L16" , "L17" , 523 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "loyaent_l17" , "LoyaEnt" , "L17" , 519 , "east" , "true" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l17_l35" , "L17" , "L35" , 1 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l16_l35" , "L16" , "L35" , 1 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l17_l18" , "L17" , "L18" , 1 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "depeent_l18" , "DepeEnt" , "L18" , 66 , "east" , "true" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l18_l19" , "L18" , "L19" , 1 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l19_l20" , "L19" , "L20" , 1 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l20_l21" , "L20" , "L21" , 349 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "exceent_l21" , "ExceEnt" , "L21" , 380 , "east" , "true" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l21_l22" , "L21" , "L22" , 1 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l22_l23" , "L22" , "L23" , 1 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l23_l24" , "L23" , "L24" , 1 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "courent_l24" , "CourEnt" , "L24" , 1 , "east" , "true" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l24_l25" , "L24" , "L25" , 1 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "enduent_l25" , "EnduEnt" , "L25" , 1 , "east" , "true" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l25_l26" , "L25" , "L26" , 1 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l26_l27" , "L26" , "L27" , 1 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l27_l28" , "L27" , "L28" , 1 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l28_l22" , "L28" , "L22" , 1 , "easrt" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l20_l29" , "L20" , "L29" , 99999 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l29_l30" , "L29" , "L30" , 99999 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l30_l31" , "L30" , "L31" , 99999 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "l31_l32" , "L31" , "L32" , 99999 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );