INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "EnthEnt-L1" , "EnthEnt" , "L1" , 275 , "east" , "true" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L1-L2" , "l1" , "l2" , 381 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "JustEnt-L3" , "JustEnt" , "L3" , 156 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L2-L3" , "L2" , "L3" , 464 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L3-L4" , "L3" , "L4" , 462 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "LearEnt-L4" , "LearEnt" , "L4" , 175 , "east" , "true" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L4-L5" , "L4" , "L5" , 601 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L5-L6" , "L5" , "L6" , 1001 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L6-L7" , "L6" , "L7" , 1057 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "CertEnt-L7" , "CertEnt" , "L7" , 759 , "east" , "true" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L7-L8" , "L7" , "L8" , 1030 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L8-L9" , "L8" , "L9" , 99999 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L9-L10" , "L9" , "L10" , 99999 , "west" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L10-L11" , "L10" , "L11" , 99999 , "west" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L8-L11" , "L8" , "L11" , 935 , "west" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "InteEnt-L11" , "InteEnt" , "L11" , 742 , "west" , "true" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L11-L12" , "L11" , "L12" , 943 , "west" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "InitEnt-L12" , "InitEnt" , "L12" , 262 , "west" , "true" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "LeadEnt-L13" , "LeadEnt" , "L13" , 82 , "east" , "true" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L13-L14" , "L13" , "L14" , 454 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "JudgEnt-L14" , "JudgEnt" , "L14" , 438 , "east" , "true" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L14-L15" , "L14" , "L15" , 321 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "RespEnt-L15" , "RespEnt" , "L15" , 854 , "east" , "true" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L15-L16" , "L15" , "L16" , 662 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L16-L17" , "L16" , "L17" , 523 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "LoyaEnt-L17" , "LoyaEnt" , "L17" , 519 , "east" , "true" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L17-L35" , "L17" , "L35" , 1 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L16-L35" , "L16" , "L35" , 1 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L17-L18" , "L17" , "L18" , 1 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "DepeEnt-L18" , "DepeEnt" , "L18" , 66 , "east" , "true" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L18-L19" , "L18" , "L19" , 1 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L19-L20" , "L19" , "L20" , 1 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L20-L21" , "L20" , "L21" , 349 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "ExceEnt-L21" , "ExceEnt" , "L21" , 380 , "east" , "true" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L21-L22" , "L21" , "L22" , 1 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L22-L23" , "L22" , "L23" , 1 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L23-L24" , "L23" , "L24" , 1 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "CourEnt-L24" , "CourEnt" , "L24" , 1 , "east" , "true" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L24-L25" , "L24" , "L25" , 1 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "EnduEnt-L25" , "EnduEnt" , "L25" , 1 , "east" , "true" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L25-L26" , "L25" , "L26" , 1 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L26-L27" , "L26" , "L27" , 1 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L27-L28" , "L27" , "L28" , 1 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L28-L22" , "L28" , "L22" , 1 , "easrt" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L20-L29" , "L20" , "L29" , 99999 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L29-L30" , "L29" , "L30" , 99999 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L30-L31" , "L30" , "L31" , 99999 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L31-L32" , "L31" , "L32" , 99999 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L32-L33" , "L32" , "L33" , 99999 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L33-L34" , "L33" , "L34" , 99999 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "L34-L35" , "L34" , "L35" , 99999 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "InitEnt-InteEnt" , "InitEnt" , "InteEnt" , 744 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "InteEnt-CertEnt" , "InteEnt" , "CertEnt" , 541 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "CertEnt-LearEnt" , "CertEnt" , "LearEnt" , 664 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "JustEnt-LearEnt" , "JustEnt" , "LearEnt" , 634 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "JustEnt-EnthEnt" , "JustEnt" , "EnthEnt" , 503 , "east" , "false" );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( "" , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );
INSERT INTO "segments" ( _id , pointa , pointb , segmentlength , segmenttype, isentrance ) VALUES ( " " , " " , " " , 438 , " " , " " );