INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '1' , '001' , 'EnthEnt' , 'Location' , '036' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '2' , '002' , 'JustEnt' , 'Location' , '037' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '3' , '003' , 'LearEnt' , 'Location' , '038' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '4' , '004' , 'CertEnt' , 'Location' , '039' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '5' , '005' , 'InteEnt' , 'Location' , '040' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '6' , '006' , 'IntiEnt' , 'Location' , '041' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '7' , '007' , 'LeadEnt' , 'Location' , '042' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '8' , '008' , 'JudgEnt' , 'Location' , '043' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '9' , '009' , 'RespEnt' , 'Location' , '044' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '10' , '010' , 'LoyaEnt' , 'Location' , '045' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '11' , '011' , 'DepeEnt' , 'Location' , '046' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '12' , '012' , 'ExceEnt' , 'Location' , '047' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '13' , '013' , 'CourEnt' , 'Location' , '048' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '14' , '014' , 'EnduEnt' , 'Location' , '049' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '15' , '015' , 'L1' , 'Location' , '001' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '16' , '016' , 'L2' , 'Location' , '002' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '17' , '017' , 'L3' , 'Location' , '003' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '18' , '018' , 'L4' , 'Location' , '004' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '19' , '019' , 'L5' , 'Location' , '005' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '20' , '020' , 'L6' , 'Location' , '006' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '21' , '021' , 'L7' , 'Location' , '007' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '22' , '022' , 'L8' , 'Location' , '008' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '23' , '023' , 'L9' , 'Location' , '009' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '24' , '024' , 'L10' , 'Location' , '010' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '25' , '025' , 'L11' , 'Location' , '011' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '26' , '026' , 'L12' , 'Location' , '012' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '27' , '027' , 'L13' , 'Location' , '013' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '28' , '028' , 'L14' , 'Location' , '014' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '29' , '029' , 'L15' , 'Location' , '015' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '30' , '030' , 'L16' , 'Location' , '016' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '31' , '031' , 'L17' , 'Location' , '017' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '32' , '032' , 'L18' , 'Location' , '018' );
INSERT INTO "qrinfo"( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '33' , '033' , 'L19' , 'Location' , '019' );
INSERT INTO "qrinfo" ( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '34' , '034' , 'L20' , 'Location' , '020' );
INSERT INTO "qrinfo" ( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '35' , '035' , 'L21' , 'Location' , '021' );
INSERT INTO "qrinfo" ( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '36' , '036' , 'L22' , 'Location' , '022' );
INSERT INTO "qrinfo" ( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '37' , '037' , 'L23' , 'Location' , '023' );
INSERT INTO "qrinfo" ( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '38' , '038' , 'L24' , 'Location' , '024' );
INSERT INTO "qrinfo" ( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '39' , '039' , 'L25' , 'Location' , '025' );
INSERT INTO "qrinfo" ( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '40' , '040' , 'L26' , 'Location' , '026' );
INSERT INTO "qrinfo" ( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '41' , '041' , 'L27' , 'Location' , '027' );
INSERT INTO "qrinfo" ( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '42' , '042' , 'L28' , 'Location' , '028' );
INSERT INTO "qrinfo" ( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '43' , '043' , 'L29' , 'Location' , '029' );
INSERT INTO "qrinfo" ( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '44' , '044' , 'L30' , 'Location' , '030' );
INSERT INTO "qrinfo" ( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '45' , '045' , 'L31' , 'Location' , '031' );
INSERT INTO "qrinfo" ( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '46' , '046' , 'L32' , 'Location' , '032' );
INSERT INTO "qrinfo" ( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '47' , '047' , 'L33' , 'Location' , '033' );
INSERT INTO "qrinfo" ( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '48' , '048' , 'L34' , 'Location' , '034' );
INSERT INTO "qrinfo" ( _id, qrid , qrcode , qrtype , qrtypedid ) VALUES ( '49' , '049' , 'L35' , 'Location' , '035' );